"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023 LiveKit, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AudioCodec:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AudioCodecEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AudioCodec.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DEFAULT_AC: _AudioCodec.ValueType  # 0
    OPUS: _AudioCodec.ValueType  # 1
    AAC: _AudioCodec.ValueType  # 2

class AudioCodec(_AudioCodec, metaclass=_AudioCodecEnumTypeWrapper): ...

DEFAULT_AC: AudioCodec.ValueType  # 0
OPUS: AudioCodec.ValueType  # 1
AAC: AudioCodec.ValueType  # 2
global___AudioCodec = AudioCodec

class _VideoCodec:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _VideoCodecEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VideoCodec.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DEFAULT_VC: _VideoCodec.ValueType  # 0
    H264_BASELINE: _VideoCodec.ValueType  # 1
    H264_MAIN: _VideoCodec.ValueType  # 2
    H264_HIGH: _VideoCodec.ValueType  # 3
    VP8: _VideoCodec.ValueType  # 4

class VideoCodec(_VideoCodec, metaclass=_VideoCodecEnumTypeWrapper): ...

DEFAULT_VC: VideoCodec.ValueType  # 0
H264_BASELINE: VideoCodec.ValueType  # 1
H264_MAIN: VideoCodec.ValueType  # 2
H264_HIGH: VideoCodec.ValueType  # 3
VP8: VideoCodec.ValueType  # 4
global___VideoCodec = VideoCodec

class _ImageCodec:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ImageCodecEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ImageCodec.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IC_DEFAULT: _ImageCodec.ValueType  # 0
    IC_JPEG: _ImageCodec.ValueType  # 1

class ImageCodec(_ImageCodec, metaclass=_ImageCodecEnumTypeWrapper): ...

IC_DEFAULT: ImageCodec.ValueType  # 0
IC_JPEG: ImageCodec.ValueType  # 1
global___ImageCodec = ImageCodec

class _TrackType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TrackTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TrackType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AUDIO: _TrackType.ValueType  # 0
    VIDEO: _TrackType.ValueType  # 1
    DATA: _TrackType.ValueType  # 2

class TrackType(_TrackType, metaclass=_TrackTypeEnumTypeWrapper): ...

AUDIO: TrackType.ValueType  # 0
VIDEO: TrackType.ValueType  # 1
DATA: TrackType.ValueType  # 2
global___TrackType = TrackType

class _TrackSource:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TrackSourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TrackSource.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _TrackSource.ValueType  # 0
    CAMERA: _TrackSource.ValueType  # 1
    MICROPHONE: _TrackSource.ValueType  # 2
    SCREEN_SHARE: _TrackSource.ValueType  # 3
    SCREEN_SHARE_AUDIO: _TrackSource.ValueType  # 4

class TrackSource(_TrackSource, metaclass=_TrackSourceEnumTypeWrapper): ...

UNKNOWN: TrackSource.ValueType  # 0
CAMERA: TrackSource.ValueType  # 1
MICROPHONE: TrackSource.ValueType  # 2
SCREEN_SHARE: TrackSource.ValueType  # 3
SCREEN_SHARE_AUDIO: TrackSource.ValueType  # 4
global___TrackSource = TrackSource

class _VideoQuality:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _VideoQualityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VideoQuality.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOW: _VideoQuality.ValueType  # 0
    MEDIUM: _VideoQuality.ValueType  # 1
    HIGH: _VideoQuality.ValueType  # 2
    OFF: _VideoQuality.ValueType  # 3

class VideoQuality(_VideoQuality, metaclass=_VideoQualityEnumTypeWrapper): ...

LOW: VideoQuality.ValueType  # 0
MEDIUM: VideoQuality.ValueType  # 1
HIGH: VideoQuality.ValueType  # 2
OFF: VideoQuality.ValueType  # 3
global___VideoQuality = VideoQuality

class _ConnectionQuality:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ConnectionQualityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ConnectionQuality.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    POOR: _ConnectionQuality.ValueType  # 0
    GOOD: _ConnectionQuality.ValueType  # 1
    EXCELLENT: _ConnectionQuality.ValueType  # 2

class ConnectionQuality(_ConnectionQuality, metaclass=_ConnectionQualityEnumTypeWrapper): ...

POOR: ConnectionQuality.ValueType  # 0
GOOD: ConnectionQuality.ValueType  # 1
EXCELLENT: ConnectionQuality.ValueType  # 2
global___ConnectionQuality = ConnectionQuality

class _ClientConfigSetting:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ClientConfigSettingEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ClientConfigSetting.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSET: _ClientConfigSetting.ValueType  # 0
    DISABLED: _ClientConfigSetting.ValueType  # 1
    ENABLED: _ClientConfigSetting.ValueType  # 2

class ClientConfigSetting(_ClientConfigSetting, metaclass=_ClientConfigSettingEnumTypeWrapper): ...

UNSET: ClientConfigSetting.ValueType  # 0
DISABLED: ClientConfigSetting.ValueType  # 1
ENABLED: ClientConfigSetting.ValueType  # 2
global___ClientConfigSetting = ClientConfigSetting

class _DisconnectReason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DisconnectReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DisconnectReason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN_REASON: _DisconnectReason.ValueType  # 0
    CLIENT_INITIATED: _DisconnectReason.ValueType  # 1
    DUPLICATE_IDENTITY: _DisconnectReason.ValueType  # 2
    SERVER_SHUTDOWN: _DisconnectReason.ValueType  # 3
    PARTICIPANT_REMOVED: _DisconnectReason.ValueType  # 4
    ROOM_DELETED: _DisconnectReason.ValueType  # 5
    STATE_MISMATCH: _DisconnectReason.ValueType  # 6
    JOIN_FAILURE: _DisconnectReason.ValueType  # 7

class DisconnectReason(_DisconnectReason, metaclass=_DisconnectReasonEnumTypeWrapper): ...

UNKNOWN_REASON: DisconnectReason.ValueType  # 0
CLIENT_INITIATED: DisconnectReason.ValueType  # 1
DUPLICATE_IDENTITY: DisconnectReason.ValueType  # 2
SERVER_SHUTDOWN: DisconnectReason.ValueType  # 3
PARTICIPANT_REMOVED: DisconnectReason.ValueType  # 4
ROOM_DELETED: DisconnectReason.ValueType  # 5
STATE_MISMATCH: DisconnectReason.ValueType  # 6
JOIN_FAILURE: DisconnectReason.ValueType  # 7
global___DisconnectReason = DisconnectReason

class _ReconnectReason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ReconnectReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ReconnectReason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RR_UNKNOWN: _ReconnectReason.ValueType  # 0
    RR_SIGNAL_DISCONNECTED: _ReconnectReason.ValueType  # 1
    RR_PUBLISHER_FAILED: _ReconnectReason.ValueType  # 2
    RR_SUBSCRIBER_FAILED: _ReconnectReason.ValueType  # 3
    RR_SWITCH_CANDIDATE: _ReconnectReason.ValueType  # 4

class ReconnectReason(_ReconnectReason, metaclass=_ReconnectReasonEnumTypeWrapper): ...

RR_UNKNOWN: ReconnectReason.ValueType  # 0
RR_SIGNAL_DISCONNECTED: ReconnectReason.ValueType  # 1
RR_PUBLISHER_FAILED: ReconnectReason.ValueType  # 2
RR_SUBSCRIBER_FAILED: ReconnectReason.ValueType  # 3
RR_SWITCH_CANDIDATE: ReconnectReason.ValueType  # 4
global___ReconnectReason = ReconnectReason

class _SubscriptionError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SubscriptionErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SubscriptionError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SE_UNKNOWN: _SubscriptionError.ValueType  # 0
    SE_CODEC_UNSUPPORTED: _SubscriptionError.ValueType  # 1
    SE_TRACK_NOTFOUND: _SubscriptionError.ValueType  # 2

class SubscriptionError(_SubscriptionError, metaclass=_SubscriptionErrorEnumTypeWrapper): ...

SE_UNKNOWN: SubscriptionError.ValueType  # 0
SE_CODEC_UNSUPPORTED: SubscriptionError.ValueType  # 1
SE_TRACK_NOTFOUND: SubscriptionError.ValueType  # 2
global___SubscriptionError = SubscriptionError

@typing_extensions.final
class Room(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    EMPTY_TIMEOUT_FIELD_NUMBER: builtins.int
    MAX_PARTICIPANTS_FIELD_NUMBER: builtins.int
    CREATION_TIME_FIELD_NUMBER: builtins.int
    TURN_PASSWORD_FIELD_NUMBER: builtins.int
    ENABLED_CODECS_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    NUM_PARTICIPANTS_FIELD_NUMBER: builtins.int
    NUM_PUBLISHERS_FIELD_NUMBER: builtins.int
    ACTIVE_RECORDING_FIELD_NUMBER: builtins.int
    sid: builtins.str
    name: builtins.str
    empty_timeout: builtins.int
    max_participants: builtins.int
    creation_time: builtins.int
    turn_password: builtins.str
    @property
    def enabled_codecs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Codec]: ...
    metadata: builtins.str
    num_participants: builtins.int
    num_publishers: builtins.int
    active_recording: builtins.bool
    def __init__(
        self,
        *,
        sid: builtins.str = ...,
        name: builtins.str = ...,
        empty_timeout: builtins.int = ...,
        max_participants: builtins.int = ...,
        creation_time: builtins.int = ...,
        turn_password: builtins.str = ...,
        enabled_codecs: collections.abc.Iterable[global___Codec] | None = ...,
        metadata: builtins.str = ...,
        num_participants: builtins.int = ...,
        num_publishers: builtins.int = ...,
        active_recording: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["active_recording", b"active_recording", "creation_time", b"creation_time", "empty_timeout", b"empty_timeout", "enabled_codecs", b"enabled_codecs", "max_participants", b"max_participants", "metadata", b"metadata", "name", b"name", "num_participants", b"num_participants", "num_publishers", b"num_publishers", "sid", b"sid", "turn_password", b"turn_password"]) -> None: ...

global___Room = Room

@typing_extensions.final
class Codec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MIME_FIELD_NUMBER: builtins.int
    FMTP_LINE_FIELD_NUMBER: builtins.int
    mime: builtins.str
    fmtp_line: builtins.str
    def __init__(
        self,
        *,
        mime: builtins.str = ...,
        fmtp_line: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fmtp_line", b"fmtp_line", "mime", b"mime"]) -> None: ...

global___Codec = Codec

@typing_extensions.final
class PlayoutDelay(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    min: builtins.int
    max: builtins.int
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        min: builtins.int = ...,
        max: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["enabled", b"enabled", "max", b"max", "min", b"min"]) -> None: ...

global___PlayoutDelay = PlayoutDelay

@typing_extensions.final
class ParticipantPermission(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CAN_SUBSCRIBE_FIELD_NUMBER: builtins.int
    CAN_PUBLISH_FIELD_NUMBER: builtins.int
    CAN_PUBLISH_DATA_FIELD_NUMBER: builtins.int
    CAN_PUBLISH_SOURCES_FIELD_NUMBER: builtins.int
    HIDDEN_FIELD_NUMBER: builtins.int
    RECORDER_FIELD_NUMBER: builtins.int
    CAN_UPDATE_METADATA_FIELD_NUMBER: builtins.int
    can_subscribe: builtins.bool
    """allow participant to subscribe to other tracks in the room"""
    can_publish: builtins.bool
    """allow participant to publish new tracks to room"""
    can_publish_data: builtins.bool
    """allow participant to publish data"""
    @property
    def can_publish_sources(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___TrackSource.ValueType]:
        """sources that are allowed to be published"""
    hidden: builtins.bool
    """indicates that it's hidden to others"""
    recorder: builtins.bool
    """indicates it's a recorder instance"""
    can_update_metadata: builtins.bool
    """indicates that participant can update own metadata"""
    def __init__(
        self,
        *,
        can_subscribe: builtins.bool = ...,
        can_publish: builtins.bool = ...,
        can_publish_data: builtins.bool = ...,
        can_publish_sources: collections.abc.Iterable[global___TrackSource.ValueType] | None = ...,
        hidden: builtins.bool = ...,
        recorder: builtins.bool = ...,
        can_update_metadata: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["can_publish", b"can_publish", "can_publish_data", b"can_publish_data", "can_publish_sources", b"can_publish_sources", "can_subscribe", b"can_subscribe", "can_update_metadata", b"can_update_metadata", "hidden", b"hidden", "recorder", b"recorder"]) -> None: ...

global___ParticipantPermission = ParticipantPermission

@typing_extensions.final
class ParticipantInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _State:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ParticipantInfo._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        JOINING: ParticipantInfo._State.ValueType  # 0
        """websocket' connected, but not offered yet"""
        JOINED: ParticipantInfo._State.ValueType  # 1
        """server received client offer"""
        ACTIVE: ParticipantInfo._State.ValueType  # 2
        """ICE connectivity established"""
        DISCONNECTED: ParticipantInfo._State.ValueType  # 3
        """WS disconnected"""

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    JOINING: ParticipantInfo.State.ValueType  # 0
    """websocket' connected, but not offered yet"""
    JOINED: ParticipantInfo.State.ValueType  # 1
    """server received client offer"""
    ACTIVE: ParticipantInfo.State.ValueType  # 2
    """ICE connectivity established"""
    DISCONNECTED: ParticipantInfo.State.ValueType  # 3
    """WS disconnected"""

    SID_FIELD_NUMBER: builtins.int
    IDENTITY_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    TRACKS_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    JOINED_AT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PERMISSION_FIELD_NUMBER: builtins.int
    REGION_FIELD_NUMBER: builtins.int
    IS_PUBLISHER_FIELD_NUMBER: builtins.int
    sid: builtins.str
    identity: builtins.str
    state: global___ParticipantInfo.State.ValueType
    @property
    def tracks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TrackInfo]: ...
    metadata: builtins.str
    joined_at: builtins.int
    """timestamp when participant joined room, in seconds"""
    name: builtins.str
    version: builtins.int
    @property
    def permission(self) -> global___ParticipantPermission: ...
    region: builtins.str
    is_publisher: builtins.bool
    """indicates the participant has an active publisher connection
    and can publish to the server
    """
    def __init__(
        self,
        *,
        sid: builtins.str = ...,
        identity: builtins.str = ...,
        state: global___ParticipantInfo.State.ValueType = ...,
        tracks: collections.abc.Iterable[global___TrackInfo] | None = ...,
        metadata: builtins.str = ...,
        joined_at: builtins.int = ...,
        name: builtins.str = ...,
        version: builtins.int = ...,
        permission: global___ParticipantPermission | None = ...,
        region: builtins.str = ...,
        is_publisher: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["permission", b"permission"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["identity", b"identity", "is_publisher", b"is_publisher", "joined_at", b"joined_at", "metadata", b"metadata", "name", b"name", "permission", b"permission", "region", b"region", "sid", b"sid", "state", b"state", "tracks", b"tracks", "version", b"version"]) -> None: ...

global___ParticipantInfo = ParticipantInfo

@typing_extensions.final
class Encryption(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Encryption._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NONE: Encryption._Type.ValueType  # 0
        GCM: Encryption._Type.ValueType  # 1
        CUSTOM: Encryption._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    NONE: Encryption.Type.ValueType  # 0
    GCM: Encryption.Type.ValueType  # 1
    CUSTOM: Encryption.Type.ValueType  # 2

    def __init__(
        self,
    ) -> None: ...

global___Encryption = Encryption

@typing_extensions.final
class SimulcastCodecInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MIME_TYPE_FIELD_NUMBER: builtins.int
    MID_FIELD_NUMBER: builtins.int
    CID_FIELD_NUMBER: builtins.int
    LAYERS_FIELD_NUMBER: builtins.int
    mime_type: builtins.str
    mid: builtins.str
    cid: builtins.str
    @property
    def layers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VideoLayer]: ...
    def __init__(
        self,
        *,
        mime_type: builtins.str = ...,
        mid: builtins.str = ...,
        cid: builtins.str = ...,
        layers: collections.abc.Iterable[global___VideoLayer] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cid", b"cid", "layers", b"layers", "mid", b"mid", "mime_type", b"mime_type"]) -> None: ...

global___SimulcastCodecInfo = SimulcastCodecInfo

@typing_extensions.final
class TrackInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    MUTED_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    SIMULCAST_FIELD_NUMBER: builtins.int
    DISABLE_DTX_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    LAYERS_FIELD_NUMBER: builtins.int
    MIME_TYPE_FIELD_NUMBER: builtins.int
    MID_FIELD_NUMBER: builtins.int
    CODECS_FIELD_NUMBER: builtins.int
    STEREO_FIELD_NUMBER: builtins.int
    DISABLE_RED_FIELD_NUMBER: builtins.int
    ENCRYPTION_FIELD_NUMBER: builtins.int
    STREAM_FIELD_NUMBER: builtins.int
    sid: builtins.str
    type: global___TrackType.ValueType
    name: builtins.str
    muted: builtins.bool
    width: builtins.int
    """original width of video (unset for audio)
    clients may receive a lower resolution version with simulcast
    """
    height: builtins.int
    """original height of video (unset for audio)"""
    simulcast: builtins.bool
    """true if track is simulcasted"""
    disable_dtx: builtins.bool
    """true if DTX (Discontinuous Transmission) is disabled for audio"""
    source: global___TrackSource.ValueType
    """source of media"""
    @property
    def layers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VideoLayer]: ...
    mime_type: builtins.str
    """mime type of codec"""
    mid: builtins.str
    @property
    def codecs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SimulcastCodecInfo]: ...
    stereo: builtins.bool
    disable_red: builtins.bool
    """true if RED (Redundant Encoding) is disabled for audio"""
    encryption: global___Encryption.Type.ValueType
    stream: builtins.str
    def __init__(
        self,
        *,
        sid: builtins.str = ...,
        type: global___TrackType.ValueType = ...,
        name: builtins.str = ...,
        muted: builtins.bool = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        simulcast: builtins.bool = ...,
        disable_dtx: builtins.bool = ...,
        source: global___TrackSource.ValueType = ...,
        layers: collections.abc.Iterable[global___VideoLayer] | None = ...,
        mime_type: builtins.str = ...,
        mid: builtins.str = ...,
        codecs: collections.abc.Iterable[global___SimulcastCodecInfo] | None = ...,
        stereo: builtins.bool = ...,
        disable_red: builtins.bool = ...,
        encryption: global___Encryption.Type.ValueType = ...,
        stream: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["codecs", b"codecs", "disable_dtx", b"disable_dtx", "disable_red", b"disable_red", "encryption", b"encryption", "height", b"height", "layers", b"layers", "mid", b"mid", "mime_type", b"mime_type", "muted", b"muted", "name", b"name", "sid", b"sid", "simulcast", b"simulcast", "source", b"source", "stereo", b"stereo", "stream", b"stream", "type", b"type", "width", b"width"]) -> None: ...

global___TrackInfo = TrackInfo

@typing_extensions.final
class VideoLayer(google.protobuf.message.Message):
    """provide information about available spatial layers"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUALITY_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    BITRATE_FIELD_NUMBER: builtins.int
    SSRC_FIELD_NUMBER: builtins.int
    quality: global___VideoQuality.ValueType
    """for tracks with a single layer, this should be HIGH"""
    width: builtins.int
    height: builtins.int
    bitrate: builtins.int
    """target bitrate in bit per second (bps), server will measure actual"""
    ssrc: builtins.int
    def __init__(
        self,
        *,
        quality: global___VideoQuality.ValueType = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        bitrate: builtins.int = ...,
        ssrc: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bitrate", b"bitrate", "height", b"height", "quality", b"quality", "ssrc", b"ssrc", "width", b"width"]) -> None: ...

global___VideoLayer = VideoLayer

@typing_extensions.final
class DataPacket(google.protobuf.message.Message):
    """new DataPacket API"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Kind:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _KindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataPacket._Kind.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        RELIABLE: DataPacket._Kind.ValueType  # 0
        LOSSY: DataPacket._Kind.ValueType  # 1

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    RELIABLE: DataPacket.Kind.ValueType  # 0
    LOSSY: DataPacket.Kind.ValueType  # 1

    KIND_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    SPEAKER_FIELD_NUMBER: builtins.int
    kind: global___DataPacket.Kind.ValueType
    @property
    def user(self) -> global___UserPacket: ...
    @property
    def speaker(self) -> global___ActiveSpeakerUpdate: ...
    def __init__(
        self,
        *,
        kind: global___DataPacket.Kind.ValueType = ...,
        user: global___UserPacket | None = ...,
        speaker: global___ActiveSpeakerUpdate | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["speaker", b"speaker", "user", b"user", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["kind", b"kind", "speaker", b"speaker", "user", b"user", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["user", "speaker"] | None: ...

global___DataPacket = DataPacket

@typing_extensions.final
class ActiveSpeakerUpdate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPEAKERS_FIELD_NUMBER: builtins.int
    @property
    def speakers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SpeakerInfo]: ...
    def __init__(
        self,
        *,
        speakers: collections.abc.Iterable[global___SpeakerInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["speakers", b"speakers"]) -> None: ...

global___ActiveSpeakerUpdate = ActiveSpeakerUpdate

@typing_extensions.final
class SpeakerInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SID_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    ACTIVE_FIELD_NUMBER: builtins.int
    sid: builtins.str
    level: builtins.float
    """audio level, 0-1.0, 1 is loudest"""
    active: builtins.bool
    """true if speaker is currently active"""
    def __init__(
        self,
        *,
        sid: builtins.str = ...,
        level: builtins.float = ...,
        active: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["active", b"active", "level", b"level", "sid", b"sid"]) -> None: ...

global___SpeakerInfo = SpeakerInfo

@typing_extensions.final
class UserPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    PARTICIPANT_IDENTITY_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    DESTINATION_SIDS_FIELD_NUMBER: builtins.int
    DESTINATION_IDENTITIES_FIELD_NUMBER: builtins.int
    TOPIC_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    """participant ID of user that sent the message"""
    participant_identity: builtins.str
    payload: builtins.bytes
    """user defined payload"""
    @property
    def destination_sids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """the ID of the participants who will receive the message (sent to all by default)"""
    @property
    def destination_identities(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """identities of participants who will receive the message (sent to all by default)"""
    topic: builtins.str
    """topic under which the message was published"""
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        participant_identity: builtins.str = ...,
        payload: builtins.bytes = ...,
        destination_sids: collections.abc.Iterable[builtins.str] | None = ...,
        destination_identities: collections.abc.Iterable[builtins.str] | None = ...,
        topic: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_topic", b"_topic", "topic", b"topic"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_topic", b"_topic", "destination_identities", b"destination_identities", "destination_sids", b"destination_sids", "participant_identity", b"participant_identity", "participant_sid", b"participant_sid", "payload", b"payload", "topic", b"topic"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_topic", b"_topic"]) -> typing_extensions.Literal["topic"] | None: ...

global___UserPacket = UserPacket

@typing_extensions.final
class ParticipantTracks(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    TRACK_SIDS_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    """participant ID of participant to whom the tracks belong"""
    @property
    def track_sids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        track_sids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sid", b"participant_sid", "track_sids", b"track_sids"]) -> None: ...

global___ParticipantTracks = ParticipantTracks

@typing_extensions.final
class ServerInfo(google.protobuf.message.Message):
    """details about the server"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Edition:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EditionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ServerInfo._Edition.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Standard: ServerInfo._Edition.ValueType  # 0
        Cloud: ServerInfo._Edition.ValueType  # 1

    class Edition(_Edition, metaclass=_EditionEnumTypeWrapper): ...
    Standard: ServerInfo.Edition.ValueType  # 0
    Cloud: ServerInfo.Edition.ValueType  # 1

    EDITION_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    REGION_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    DEBUG_INFO_FIELD_NUMBER: builtins.int
    edition: global___ServerInfo.Edition.ValueType
    version: builtins.str
    protocol: builtins.int
    region: builtins.str
    node_id: builtins.str
    debug_info: builtins.str
    """additional debugging information. sent only if server is in development mode"""
    def __init__(
        self,
        *,
        edition: global___ServerInfo.Edition.ValueType = ...,
        version: builtins.str = ...,
        protocol: builtins.int = ...,
        region: builtins.str = ...,
        node_id: builtins.str = ...,
        debug_info: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["debug_info", b"debug_info", "edition", b"edition", "node_id", b"node_id", "protocol", b"protocol", "region", b"region", "version", b"version"]) -> None: ...

global___ServerInfo = ServerInfo

@typing_extensions.final
class ClientInfo(google.protobuf.message.Message):
    """details about the client"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SDK:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SDKEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ClientInfo._SDK.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: ClientInfo._SDK.ValueType  # 0
        JS: ClientInfo._SDK.ValueType  # 1
        SWIFT: ClientInfo._SDK.ValueType  # 2
        ANDROID: ClientInfo._SDK.ValueType  # 3
        FLUTTER: ClientInfo._SDK.ValueType  # 4
        GO: ClientInfo._SDK.ValueType  # 5
        UNITY: ClientInfo._SDK.ValueType  # 6
        REACT_NATIVE: ClientInfo._SDK.ValueType  # 7
        RUST: ClientInfo._SDK.ValueType  # 8
        PYTHON: ClientInfo._SDK.ValueType  # 9
        CPP: ClientInfo._SDK.ValueType  # 10

    class SDK(_SDK, metaclass=_SDKEnumTypeWrapper): ...
    UNKNOWN: ClientInfo.SDK.ValueType  # 0
    JS: ClientInfo.SDK.ValueType  # 1
    SWIFT: ClientInfo.SDK.ValueType  # 2
    ANDROID: ClientInfo.SDK.ValueType  # 3
    FLUTTER: ClientInfo.SDK.ValueType  # 4
    GO: ClientInfo.SDK.ValueType  # 5
    UNITY: ClientInfo.SDK.ValueType  # 6
    REACT_NATIVE: ClientInfo.SDK.ValueType  # 7
    RUST: ClientInfo.SDK.ValueType  # 8
    PYTHON: ClientInfo.SDK.ValueType  # 9
    CPP: ClientInfo.SDK.ValueType  # 10

    SDK_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    OS_FIELD_NUMBER: builtins.int
    OS_VERSION_FIELD_NUMBER: builtins.int
    DEVICE_MODEL_FIELD_NUMBER: builtins.int
    BROWSER_FIELD_NUMBER: builtins.int
    BROWSER_VERSION_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    sdk: global___ClientInfo.SDK.ValueType
    version: builtins.str
    protocol: builtins.int
    os: builtins.str
    os_version: builtins.str
    device_model: builtins.str
    browser: builtins.str
    browser_version: builtins.str
    address: builtins.str
    network: builtins.str
    """wifi, wired, cellular, vpn, empty if not known"""
    def __init__(
        self,
        *,
        sdk: global___ClientInfo.SDK.ValueType = ...,
        version: builtins.str = ...,
        protocol: builtins.int = ...,
        os: builtins.str = ...,
        os_version: builtins.str = ...,
        device_model: builtins.str = ...,
        browser: builtins.str = ...,
        browser_version: builtins.str = ...,
        address: builtins.str = ...,
        network: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "browser", b"browser", "browser_version", b"browser_version", "device_model", b"device_model", "network", b"network", "os", b"os", "os_version", b"os_version", "protocol", b"protocol", "sdk", b"sdk", "version", b"version"]) -> None: ...

global___ClientInfo = ClientInfo

@typing_extensions.final
class ClientConfiguration(google.protobuf.message.Message):
    """server provided client configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIDEO_FIELD_NUMBER: builtins.int
    SCREEN_FIELD_NUMBER: builtins.int
    RESUME_CONNECTION_FIELD_NUMBER: builtins.int
    DISABLED_CODECS_FIELD_NUMBER: builtins.int
    FORCE_RELAY_FIELD_NUMBER: builtins.int
    @property
    def video(self) -> global___VideoConfiguration: ...
    @property
    def screen(self) -> global___VideoConfiguration: ...
    resume_connection: global___ClientConfigSetting.ValueType
    @property
    def disabled_codecs(self) -> global___DisabledCodecs: ...
    force_relay: global___ClientConfigSetting.ValueType
    def __init__(
        self,
        *,
        video: global___VideoConfiguration | None = ...,
        screen: global___VideoConfiguration | None = ...,
        resume_connection: global___ClientConfigSetting.ValueType = ...,
        disabled_codecs: global___DisabledCodecs | None = ...,
        force_relay: global___ClientConfigSetting.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["disabled_codecs", b"disabled_codecs", "screen", b"screen", "video", b"video"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["disabled_codecs", b"disabled_codecs", "force_relay", b"force_relay", "resume_connection", b"resume_connection", "screen", b"screen", "video", b"video"]) -> None: ...

global___ClientConfiguration = ClientConfiguration

@typing_extensions.final
class VideoConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HARDWARE_ENCODER_FIELD_NUMBER: builtins.int
    hardware_encoder: global___ClientConfigSetting.ValueType
    def __init__(
        self,
        *,
        hardware_encoder: global___ClientConfigSetting.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hardware_encoder", b"hardware_encoder"]) -> None: ...

global___VideoConfiguration = VideoConfiguration

@typing_extensions.final
class DisabledCodecs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODECS_FIELD_NUMBER: builtins.int
    PUBLISH_FIELD_NUMBER: builtins.int
    @property
    def codecs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Codec]:
        """disabled for both publish and subscribe"""
    @property
    def publish(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Codec]:
        """only disable for publish"""
    def __init__(
        self,
        *,
        codecs: collections.abc.Iterable[global___Codec] | None = ...,
        publish: collections.abc.Iterable[global___Codec] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["codecs", b"codecs", "publish", b"publish"]) -> None: ...

global___DisabledCodecs = DisabledCodecs

@typing_extensions.final
class RTPDrift(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    START_TIMESTAMP_FIELD_NUMBER: builtins.int
    END_TIMESTAMP_FIELD_NUMBER: builtins.int
    RTP_CLOCK_TICKS_FIELD_NUMBER: builtins.int
    DRIFT_SAMPLES_FIELD_NUMBER: builtins.int
    DRIFT_MS_FIELD_NUMBER: builtins.int
    CLOCK_RATE_FIELD_NUMBER: builtins.int
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    duration: builtins.float
    start_timestamp: builtins.int
    end_timestamp: builtins.int
    rtp_clock_ticks: builtins.int
    drift_samples: builtins.int
    drift_ms: builtins.float
    clock_rate: builtins.float
    def __init__(
        self,
        *,
        start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        duration: builtins.float = ...,
        start_timestamp: builtins.int = ...,
        end_timestamp: builtins.int = ...,
        rtp_clock_ticks: builtins.int = ...,
        drift_samples: builtins.int = ...,
        drift_ms: builtins.float = ...,
        clock_rate: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end_time", b"end_time", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clock_rate", b"clock_rate", "drift_ms", b"drift_ms", "drift_samples", b"drift_samples", "duration", b"duration", "end_time", b"end_time", "end_timestamp", b"end_timestamp", "rtp_clock_ticks", b"rtp_clock_ticks", "start_time", b"start_time", "start_timestamp", b"start_timestamp"]) -> None: ...

global___RTPDrift = RTPDrift

@typing_extensions.final
class RTPStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class GapHistogramEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    PACKETS_FIELD_NUMBER: builtins.int
    PACKET_RATE_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    HEADER_BYTES_FIELD_NUMBER: builtins.int
    BITRATE_FIELD_NUMBER: builtins.int
    PACKETS_LOST_FIELD_NUMBER: builtins.int
    PACKET_LOSS_RATE_FIELD_NUMBER: builtins.int
    PACKET_LOSS_PERCENTAGE_FIELD_NUMBER: builtins.int
    PACKETS_DUPLICATE_FIELD_NUMBER: builtins.int
    PACKET_DUPLICATE_RATE_FIELD_NUMBER: builtins.int
    BYTES_DUPLICATE_FIELD_NUMBER: builtins.int
    HEADER_BYTES_DUPLICATE_FIELD_NUMBER: builtins.int
    BITRATE_DUPLICATE_FIELD_NUMBER: builtins.int
    PACKETS_PADDING_FIELD_NUMBER: builtins.int
    PACKET_PADDING_RATE_FIELD_NUMBER: builtins.int
    BYTES_PADDING_FIELD_NUMBER: builtins.int
    HEADER_BYTES_PADDING_FIELD_NUMBER: builtins.int
    BITRATE_PADDING_FIELD_NUMBER: builtins.int
    PACKETS_OUT_OF_ORDER_FIELD_NUMBER: builtins.int
    FRAMES_FIELD_NUMBER: builtins.int
    FRAME_RATE_FIELD_NUMBER: builtins.int
    JITTER_CURRENT_FIELD_NUMBER: builtins.int
    JITTER_MAX_FIELD_NUMBER: builtins.int
    GAP_HISTOGRAM_FIELD_NUMBER: builtins.int
    NACKS_FIELD_NUMBER: builtins.int
    NACK_ACKS_FIELD_NUMBER: builtins.int
    NACK_MISSES_FIELD_NUMBER: builtins.int
    NACK_REPEATED_FIELD_NUMBER: builtins.int
    PLIS_FIELD_NUMBER: builtins.int
    LAST_PLI_FIELD_NUMBER: builtins.int
    FIRS_FIELD_NUMBER: builtins.int
    LAST_FIR_FIELD_NUMBER: builtins.int
    RTT_CURRENT_FIELD_NUMBER: builtins.int
    RTT_MAX_FIELD_NUMBER: builtins.int
    KEY_FRAMES_FIELD_NUMBER: builtins.int
    LAST_KEY_FRAME_FIELD_NUMBER: builtins.int
    LAYER_LOCK_PLIS_FIELD_NUMBER: builtins.int
    LAST_LAYER_LOCK_PLI_FIELD_NUMBER: builtins.int
    PACKET_DRIFT_FIELD_NUMBER: builtins.int
    REPORT_DRIFT_FIELD_NUMBER: builtins.int
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    duration: builtins.float
    packets: builtins.int
    packet_rate: builtins.float
    bytes: builtins.int
    header_bytes: builtins.int
    bitrate: builtins.float
    packets_lost: builtins.int
    packet_loss_rate: builtins.float
    packet_loss_percentage: builtins.float
    packets_duplicate: builtins.int
    packet_duplicate_rate: builtins.float
    bytes_duplicate: builtins.int
    header_bytes_duplicate: builtins.int
    bitrate_duplicate: builtins.float
    packets_padding: builtins.int
    packet_padding_rate: builtins.float
    bytes_padding: builtins.int
    header_bytes_padding: builtins.int
    bitrate_padding: builtins.float
    packets_out_of_order: builtins.int
    frames: builtins.int
    frame_rate: builtins.float
    jitter_current: builtins.float
    jitter_max: builtins.float
    @property
    def gap_histogram(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, builtins.int]: ...
    nacks: builtins.int
    nack_acks: builtins.int
    nack_misses: builtins.int
    nack_repeated: builtins.int
    plis: builtins.int
    @property
    def last_pli(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    firs: builtins.int
    @property
    def last_fir(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    rtt_current: builtins.int
    rtt_max: builtins.int
    key_frames: builtins.int
    @property
    def last_key_frame(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    layer_lock_plis: builtins.int
    @property
    def last_layer_lock_pli(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def packet_drift(self) -> global___RTPDrift: ...
    @property
    def report_drift(self) -> global___RTPDrift:
        """NEXT_ID: 46"""
    def __init__(
        self,
        *,
        start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        duration: builtins.float = ...,
        packets: builtins.int = ...,
        packet_rate: builtins.float = ...,
        bytes: builtins.int = ...,
        header_bytes: builtins.int = ...,
        bitrate: builtins.float = ...,
        packets_lost: builtins.int = ...,
        packet_loss_rate: builtins.float = ...,
        packet_loss_percentage: builtins.float = ...,
        packets_duplicate: builtins.int = ...,
        packet_duplicate_rate: builtins.float = ...,
        bytes_duplicate: builtins.int = ...,
        header_bytes_duplicate: builtins.int = ...,
        bitrate_duplicate: builtins.float = ...,
        packets_padding: builtins.int = ...,
        packet_padding_rate: builtins.float = ...,
        bytes_padding: builtins.int = ...,
        header_bytes_padding: builtins.int = ...,
        bitrate_padding: builtins.float = ...,
        packets_out_of_order: builtins.int = ...,
        frames: builtins.int = ...,
        frame_rate: builtins.float = ...,
        jitter_current: builtins.float = ...,
        jitter_max: builtins.float = ...,
        gap_histogram: collections.abc.Mapping[builtins.int, builtins.int] | None = ...,
        nacks: builtins.int = ...,
        nack_acks: builtins.int = ...,
        nack_misses: builtins.int = ...,
        nack_repeated: builtins.int = ...,
        plis: builtins.int = ...,
        last_pli: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        firs: builtins.int = ...,
        last_fir: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        rtt_current: builtins.int = ...,
        rtt_max: builtins.int = ...,
        key_frames: builtins.int = ...,
        last_key_frame: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        layer_lock_plis: builtins.int = ...,
        last_layer_lock_pli: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        packet_drift: global___RTPDrift | None = ...,
        report_drift: global___RTPDrift | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end_time", b"end_time", "last_fir", b"last_fir", "last_key_frame", b"last_key_frame", "last_layer_lock_pli", b"last_layer_lock_pli", "last_pli", b"last_pli", "packet_drift", b"packet_drift", "report_drift", b"report_drift", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bitrate", b"bitrate", "bitrate_duplicate", b"bitrate_duplicate", "bitrate_padding", b"bitrate_padding", "bytes", b"bytes", "bytes_duplicate", b"bytes_duplicate", "bytes_padding", b"bytes_padding", "duration", b"duration", "end_time", b"end_time", "firs", b"firs", "frame_rate", b"frame_rate", "frames", b"frames", "gap_histogram", b"gap_histogram", "header_bytes", b"header_bytes", "header_bytes_duplicate", b"header_bytes_duplicate", "header_bytes_padding", b"header_bytes_padding", "jitter_current", b"jitter_current", "jitter_max", b"jitter_max", "key_frames", b"key_frames", "last_fir", b"last_fir", "last_key_frame", b"last_key_frame", "last_layer_lock_pli", b"last_layer_lock_pli", "last_pli", b"last_pli", "layer_lock_plis", b"layer_lock_plis", "nack_acks", b"nack_acks", "nack_misses", b"nack_misses", "nack_repeated", b"nack_repeated", "nacks", b"nacks", "packet_drift", b"packet_drift", "packet_duplicate_rate", b"packet_duplicate_rate", "packet_loss_percentage", b"packet_loss_percentage", "packet_loss_rate", b"packet_loss_rate", "packet_padding_rate", b"packet_padding_rate", "packet_rate", b"packet_rate", "packets", b"packets", "packets_duplicate", b"packets_duplicate", "packets_lost", b"packets_lost", "packets_out_of_order", b"packets_out_of_order", "packets_padding", b"packets_padding", "plis", b"plis", "report_drift", b"report_drift", "rtt_current", b"rtt_current", "rtt_max", b"rtt_max", "start_time", b"start_time"]) -> None: ...

global___RTPStats = RTPStats

@typing_extensions.final
class TimedVersion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIX_MICRO_FIELD_NUMBER: builtins.int
    TICKS_FIELD_NUMBER: builtins.int
    unix_micro: builtins.int
    ticks: builtins.int
    def __init__(
        self,
        *,
        unix_micro: builtins.int = ...,
        ticks: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ticks", b"ticks", "unix_micro", b"unix_micro"]) -> None: ...

global___TimedVersion = TimedVersion
