#!/usr/bin/env python3
import json
import os
import pathlib
import sys

# ensure 2 args
if len(sys.argv) != 3:
    print("error: package path and name must be specified")
    sys.exit(22)

root = pathlib.Path(__file__).parent.parent.resolve()

# read version from package.json
with open(os.path.join(root, sys.argv[1], "package.json"), "r") as f:
    version = json.load(f)["version"]

# write new version to file
with open(os.path.join(root, sys.argv[1], *sys.argv[2].split("."), "version.py"), "w") as f:
    f.write(f"""# Copyright 2024 LiveKit, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

__version__ = "{version}"
""")
