FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y curl

RUN pip install --no-cache-dir uv

WORKDIR /app
# COPY . /app

RUN uv sync --all-extras --dev

CMD ["/app/tests/run_proxied_tests.sh"]