name: Check Types 

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install mypy 
      run: python -m pip install --upgrade mypy 

    - name: Install all packages
      run: |
        find . -name setup.py | xargs -n 1 dirname | xargs -n 1 python -m pip install

    - name: Check Types 
      # run : |
      #   mypy -p livekit.agents \
      #        -p livekit.plugins.openai \
      #        -p livekit.plugins.deepgram \
      #        -p livekit.plugins.google \
      #        -p livekit.plugins.nltk \
      #        -p livekit.plugins.silero \
      #        -p livekit.plugins.elevenlabs \
      #        -p livekit.plugins.cartesia
      run: |
        for d in $(find . -name setup.py | xargs -n 1 dirname | xargs -n 1 basename); do
          echo "Checking types for package: $d"
          mypy -p $d
        done
