name: Check Types 

on: push

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install mypy 
      run: python -m pip install --upgrade mypy 

    - name: Install all packages
      run: |
        pip install ./livekit-plugins/livekit-plugins-openai
  # find . -name setup.py | xargs -n 1 dirname | xargs -n 1 python -m pip install

    - name: Check Types 
      run : |
        mypy --non-interactive --install-type -p livekit-plugins-openai
 #     run: |
 #       for d in $(find . -name setup.py | xargs -n 1 dirname | xargs -n 1 basename); do
 #         echo "Checking types for package: $d"
 #         python -m mypy --non-interactive --install-type -p '$d'
 #       done