name: Exit pre-release mode

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  enter-pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Enter pre-release mode
        run: |
          pnpm changeset pre exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '[".changeset"]'
          default_author: github_actions
          message: exit pre-release mode
