# This workflow will upload a Python Package using Twine when manually dispatched
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Manual package publish (for special cirumstances only)

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'The name of the package to publish'
        required: true

permissions:
  contents: read

jobs:
  build:

    defaults:
      run:
        working-directory: ${{ contains(inputs.package_name, 'plugins') && format('livekit-plugins/{0}', inputs.package_name) || 'livekit-agents' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: ${{ contains(inputs.package_name, 'plugins') && format('livekit-plugins/{0}', inputs.package_name) || 'livekit-agents' }}/dist

  publish:

    needs:
    - build

    runs-on: ubuntu-latest

    steps:

    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}