name: Publish livekit-plugins-nltk

on:
  workflow_dispatch

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish-package.yml
    with:
      package_name: 'livekit-plugins/livekit-plugins-nltk'
      package_module: 'livekit.plugins.nltk'
    secrets: inherit
