name: Publish livekit-plugins-google

on:
  workflow_dispatch

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish-package.yml
    with:
      package_name: 'livekit-plugins/livekit-plugins-google'
      package_module: 'livekit.plugins.google'
    secrets: inherit
