name: Publish livekit-plugins-google

on:
  push:
    branches:
      - main

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish-package.yml
    with:
      package_name: 'livekit-plugins/livekit-plugins-google'
