name: Publish livekit-plugins-azure

on:
  workflow_dispatch

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish-package.yml
    with:
      package_name: 'livekit-plugins/livekit-plugins-azure'
      package_module: 'livekit.plugins.azure'
    secrets: inherit
