name: Publish livekit-plugins-cartesia

on:
  workflow_dispatch

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish-package.yml
    with:
      package_name: 'livekit-plugins/livekit-plugins-cartesia'
      package_module: 'livekit.plugins.cartesia'
    secrets: inherit
