name: Publish livekit-plugins-silero

on:
  workflow_dispatch

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish-package.yml
    with:
      package_name: 'livekit-plugins/livekit-plugins-silero'
      package_module: 'livekit.plugins.silero'
    secrets: inherit
