name: Publish docs

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCS_DEPLOY_AWS_ACCESS_KEY: {}
      DOCS_DEPLOY_AWS_API_SECRET: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          submodules: true
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install package, plugins, and docs dependencies
        run: |
          uv sync --all-extras --group docs

      - name: Build HTML Docs
        run: |
          uv run --active pdoc --skip-errors --html --output-dir=docs livekit

      - name: Build Markdown Docs
        run: |
          uv run --active python .github/convert_html_docs.py docs/ docs-md -v --check-links

      - name: S3 Upload
        run: |
          aws s3 sync --delete docs/ s3://livekit-docs/python
          aws s3 sync --delete docs-md/ s3://livekit-docs/python-md
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOY_AWS_API_SECRET }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Expire cloudfront cache
        run: |
          aws cloudfront create-invalidation --distribution-id EJJ40KLJ3TRY9 --paths "/python/*" "/python-md/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOY_AWS_API_SECRET }}
          AWS_DEFAULT_REGION: "us-east-1"
