name: Publish livekit-agents

on:
  workflow_dispatch

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish-package.yml
    with:
      package_name: 'livekit-agents'
      docs_entrypoint: 'livekit-agents/livekit/agents'
    secrets: inherit
