# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/deepfake_streaming/streaming.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class DeepfakeStreamingSchemaResultEventType(betterproto.Enum):
    UNKNOWN = 0
    SUSPICIOUS = 1
    CLEAR = 2
    ERROR = 3
    ALERT = 4


class DeepfakeStreamingSchemaFrameRequestFormat(betterproto.Enum):
    JPEG = 0
    WEBP = 1


@dataclass(eq=False, repr=False)
class DeepfakeStreamingSchema(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DeepfakeStreamingSchemaResultEvent(betterproto.Message):
    type: "DeepfakeStreamingSchemaResultEventType" = betterproto.enum_field(1)
    participant_id: str = betterproto.string_field(2)
    track_id: str = betterproto.string_field(3)
    message: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class DeepfakeStreamingSchemaAuthRequest(betterproto.Message):
    api_key: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class DeepfakeStreamingSchemaFrameRequest(betterproto.Message):
    participant_id: str = betterproto.string_field(1)
    track_id: str = betterproto.string_field(2)
    timestamp_ms: int = betterproto.int64_field(3)
    format: "DeepfakeStreamingSchemaFrameRequestFormat" = betterproto.enum_field(4)
    data: bytes = betterproto.bytes_field(5)
